### ISSUE TITLE
E-mail members copy has several mentions of "group" (and a typo)

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/openlab-theme#111]
The E-mail members page neds some copy edits. Places where changes are needed are highlighted below. Off the cuff suggestions follow.

URL e.g. http://openlabdev.commonsinabox.org/groups/front-end-testing-101/admin/notifications/

1. Top panel heading
    + Send an email notice to everyone in the group =>  Send an email notice to all members
2.  Top panel body
    1. You can use the form below to send an email notice to all group members.  => You can use the form below to send an email notice to all members. 
    2. Everyone in the group will receive the email -- regardless of their email settings -- so use with caution. => Every member will receive the email -- regardless of their email settings -- so use with caution.
3. Submit button
    + Email this notice to everyone in the group => Send to everyone
4. Second panel body
    + Send an email when a new member join the group. => Send an email when a new member joins.

![cbox-ol testing site](https://user-images.githubusercontent.com/3885628/31946418-c21e7612-b89f-11e7-9dbb-99fdcc1b6ce3.png)

**Comment by bree-z** [comment]
Hi Boone, 

Sorry, I don't see what's in the screenshot above, here's what I see for this page: http://openlabdev.commonsinabox.org/groups/political-writing/admin/notifications/

![emailmembers](https://user-images.githubusercontent.com/7189824/40075269-eecdcd6c-5849-11e8-9de1-60b9e63a259d.png)

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good!
