### ISSUE TITLE
homepage display issue: left-column headings are not displayed

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/openlab-theme#116]
The left column of the homepage is missing most of its widget headers. Only the first one is visible. The h2 tags are present but contain no inner content.

ex.

    <h2 class="title uppercase"></h2>

CBOX-OL homepage left column
![screenshot-openlabdev commonsinabox org-2017-10-24-11-16-38-279](https://user-images.githubusercontent.com/3885628/31952741-4dcd0a5c-b8af-11e7-90f3-0cfe4d5f6bd2.png)

cf. CT-OL
![screenshot-openlab citytech cuny edu-2017-10-24-11-17-37-042](https://user-images.githubusercontent.com/3885628/31952737-4cb660f0-b8af-11e7-9f2b-899a49665aa5.png)

**Comment by bree-z** [comment]
Hi Boone -- does this need to be tested with a clean install?

Thanks!

**Comment by boonebgorges** [comment]
Yes, and I've just retested. In the interest of clearing the milestone, I'm closing this out.
