### ISSUE TITLE
Update color schemes

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#134]
From Jenna https://www.dropbox.com/sh/3ok9zru1eos7mn1/AADWFiIdd_QqvJL0WKRmUky9a/AccessibleColorThemes?dl=0

**Comment by bree-z** [comment]
Thanks, Boone!  These look good.  

@jennaspevack do you want to take another look?  If not, dare I say we can close this?

**Comment by bree-z** [comment]
The hover contrast for the search/filter 'Reset' button on group directory page searches is very light.  I didn't check red, but it's very hard to read (see screenshot below).  And unless I got the colors wrong, green #b6d498 on #cccccc doesn't pass AA or AAA and blue #8ccae4 on #cccccc doesn't pass AA or AAA.

<img width="395" alt="resetbuttonhovercontrast_red" src="https://user-images.githubusercontent.com/7189824/39545679-f556eed6-4e1f-11e8-9667-031c74b24e25.png">

**Comment by boonebgorges** [comment]
Thanks, @bree-z. In the interest of taking a decision off of the shoulders of @jennaspevack , I've changed the hover color of these buttons to gray. So, the background color changes on hover, but not the text color.

**Comment by jennaspevack** [comment]
@boonebgorges @bree-z: The reset hover was included in the original mockups, but probably was too subtle :) I didn't include specific hex values, but it's the same for all color schemes and is exactly what Boone describes above. 
![image](https://user-images.githubusercontent.com/22797200/40320995-98a1766c-5cfb-11e8-8e54-f81da50431bc.png)

**Comment by boonebgorges** [comment]
Excellent, thanks, @jennaspevack ! I think this just needs a test, then.

**Comment by bree-z** [comment]
Thanks, @boonebgorges and @jennaspevack !  

I also must add that as of the moment I click "Close and comment" I've officially rid the Issues > Beta page of all little yellow flags!  (For now!)  :-D
