### ISSUE TITLE
Update group home layout

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#135]
From Jenna https://www.dropbox.com/sh/3ok9zru1eos7mn1/AABLi7kqqjhE1iZG3SwEaZIka/HOMEProfile-FinalVersions?dl=0

**Comment by boonebgorges** [comment]
I'm assuming that Bree's comment above refers to d1a83c8329a18f68134d7f6d9e90293120301710. I've reverted that change.

**Comment by bree-z** [comment]
This looks good, thanks!
