### ISSUE TITLE
Implement branding/logo

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#140]
I think the correct places are:

- [x] Default logo shown at upper-left on toolbar
- [x] Dashboard
- [x] Footer

**Comment by bree-z** [comment]
Thanks, Boone.  The dashboard and footer look good to me, but how do I test the default logo?  Do we need to wait for a fresh install, or am I not understanding that one correctly?

Thanks!

**Comment by boonebgorges** [comment]
You can test the default logo either by firing up a new install, or by removing the custom logo at Dashboard > Customize > Logo.

**Comment by bree-z** [comment]
Actually, sorry, I'm reopening this just in case @jennaspevack wants to take a look.

**Comment by boonebgorges** [comment]
Closing this ticket in favor of the more recent round from Jenna and Charlie.
