### ISSUE TITLE
Move Avatar Upload to first step of group creation

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#142]
Breaking off from #138 because it's a large task.

- [x] Integrate BP's upload UI
- [x] Make necessary abstractions to allow BP to accept avatars for groups that don't yet exist
- [x] After group creation, move the dummy avatars to the correct location
- [x] Ensure that this all works during group edit
- [x] Fix the Delete functionality for group creation

**Comment by bree-z** [comment]
This has been thoroughly tested, but I'm not sure if there's anything else that needs to be done before closing it.
