### ISSUE TITLE
Brand Setting - Copy - Terms of Service missing

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/openlab-theme#143]
Hi - I noticed that "Contact Page" is repeated twice.  I think the second one should be "Terms of Service."  See attached.
![copy bug](https://user-images.githubusercontent.com/630806/37620744-7eb03d54-2b93-11e8-9f38-9c9e3ac1b132.png)

**Comment by bree-z** [comment]
This looks good, thanks!
