### ISSUE TITLE
WP Grade Comments: Private comment appears in Course Home comments feed

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#145]
Hi Boone, 

On the OpenLab, private comments don’t appear for any users (admins or non-admins) on the Course Profile.  On http://openlabdev.commonsinabox.org private comments are appearing on the Course Home for all users (or even if not logged in).  

I was testing in this course: http://openlabdev.commonsinabox.org/groups/spring-please/ 

Here’s a link to the posts with private comments:
http://openlabdev.commonsinabox.org/spring-please/2018/03/28/student-test-post/ 
http://openlabdev.commonsinabox.org/spring-please/2018/03/28/test-student-post/

Thanks!

![wpgradecomments](https://user-images.githubusercontent.com/7189824/38058091-a0132236-32af-11e8-8e00-d068046dcad7.png)

**Comment by bree-z** [comment]
Sorry Boone, for some reason I'm now able to see private comments in the feed, even when I'm not logged in.  I tried a hard refresh, and tried in two different courses.  

See for example, in this course: http://openlabdev.commonsinabox.org/groups/design-dev-test/ 

![wpgradecomments_privatecommentsvisible](https://user-images.githubusercontent.com/7189824/38893524-856b549a-4258-11e8-8d1b-a50b62d0843d.png)

**Comment by boonebgorges** [comment]
Thanks. Another attempt is ready to test.

**Comment by bree-z** [comment]
Thanks Boone!  I'm no longer seeing private comments.
