### ISSUE TITLE
Create Project Group: Return to Step 1 "loses" data

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#155]
When I press the Previous Step button from the Step 2 screen, the Step 1 screen appears, but is not populated with all of the items that I entered. The url is missing, the avatar is missing. The academic units are missing and privacy settings have returned to default.

**Comment by bree-z** [comment]
I tested all of the scenarios above and everything looks OK to me, but I'm going to come back to this just to make sure I got everything.

**Comment by bree-z** [comment]
I think we can close this one.  :)
