### ISSUE TITLE
Group Creation Projects: Error Messages

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#156]
Since these pages are long, scrolling to the Next Step/Finish button means that resulting error messages are not seen. The result is you sit and wait for something to happen. Only by scrolling back up can you see the message. This may not be a problem on production with better performance, but it might be a good idea to add a message near the button "Please correct errors highlighted above and resububmit"

**Comment by bree-z** [comment]
Thanks, Boone!  This part looks good to me.  

However, in step 2 of group creation (and settings), if I choose either 'Use an existing site' or 'Use an external site' but don't specify an existing or external site, I don't see an error message, I'm just thrown to the homepage and no site is created.

**Comment by boonebgorges** [comment]
Thanks, Bree. These fields have never had any sort of validation. I've added some. Please run each site type (existing, new, external, cloned) through its paces - I had to change the overall logic a bit. (Sorry for the extra work.)
