### ISSUE TITLE
Main site footer overlaps with footer on group sites

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#158]
I wasn't sure if this should be separate from #137 , but the footer for the main site hides the bottom of group site footers.  

e.g. **Twenty Sixteen**

![footer2016](https://user-images.githubusercontent.com/7189824/38631136-e5b624fa-3d86-11e8-8467-3fceb5c0d246.png)

**Twenty Thirteen**

![footer2013](https://user-images.githubusercontent.com/7189824/38631138-eb4932f4-3d86-11e8-9121-a8741468c78b.png)

**Comment by bree-z** [comment]
Sorry, this one slipped through the cracks.  Twenty Fifteen is still behaving strangely with the footer in certain circumstances, that appear to depend on the length of the page, or number of posts on the homepage.   I'm not sure how to explain this well, but when I scroll down to the bottom of the page, I see the footer flash for a second, and then it disappears.  I see the same thing in Firefox and Chrome (but can't get a screenshot).

- Example of a page with this behavior: http://openlabdev.commonsinabox.org/mural-club/sample-page/
- And, another: http://openlabdev.commonsinabox.org/writing-politics-sp2018-pol345/
- I think the homepage of this site looks OK because there are a lot of posts: http://openlabdev.commonsinabox.org/mural-club/

I'm not sure if this is enough to be helpful, but let me know if there's anything else I can add.  Thanks!

**Comment by boonebgorges** [comment]
Thanks, Bree. Twenty Fifteen is a nightmare and there is little that I can do to fix this in a correct way. Adding up all the time spent on this issue with Twenty Fifteen, it's been several miserable hours, with no great solution.

I've just put up a sort of hail mary onto openlabdev.commonsinabox.org. It forces the content body to always be taller than the sidebar. This is less than elegant but it does do away with the jitteriness. Can you have another look? We need to get to a point where this is good enough to be usable.

**Comment by mkgold** [comment]
Hi All -- do we integrate Twenty Fifteen into the platform itself in any way? Ie, is the theme pre-loaded and/or used for some of our site templates, like the course site template?

**Comment by boonebgorges** [comment]
Twenty Fifteen is included as part of a default WordPress installation.

**Comment by mkgold** [comment]
Okay -- thanks

**Comment by bree-z** [comment]
Thanks, Boone, and sorry for the extra headache!  

Perhaps @mkgold, @charliemedwards, or @jennaspevack should make the "good enough" determination?  Here are a few sites where you can see it:

* Example of a page with this behavior: http://openlabdev.commonsinabox.org/mural-club/sample-page/
* And, another: http://openlabdev.commonsinabox.org/writing-politics-sp2018-pol345/
* Here's a site where it looks OK - the homepage has a bunch of posts: http://openlabdev.commonsinabox.org/mural-club/

My thought is that it's not ideal, but the funkiness only happens if there's not much of anything on a page, or very few posts on the homepage, so perhaps it's not going to affect the majority of users.  Or, maybe we could include something in help about it?  I'm not sure...

**Comment by boonebgorges** [comment]
Thanks, @bree-z . Others on this ticket, please don't test anything yet. The links that Bree has posted apparently have not actually inherited the fixes that I put in place last week. I do not know why, and it will take time to investigate and reverse engineer. I will attempt to investigate this next week or the following one, as time allows.

**Comment by bree-z** [comment]
Sorry Boone!  I tried with one new site that I created today (http://openlabdev.commonsinabox.org/dirt-seminar/), and I'm still seeing the jitteriness (in FF and Chrome), except when I try to record what I'm seeing with a screencast tool!  Then, it seems OK to me.  

I don't want to complicate things more, so just fyi in case it's somehow helpful.  

I can't upload the screencast because it's in a .webm format, and I can't seem to change this in the settings.  I'm not sure it's worth trying to figure out how to get a different version.  :-/

**Comment by boonebgorges** [comment]
Yes, I'm seeing the problem too, and I don't know why. I'll have to spend more time investigating in the upcoming weeks.

**Comment by boonebgorges** [comment]
Actually, I just saw that there was a syntax error in the JS fix I'd added. Can you give another quick test after a hard refresh to see if the behavior is different?

**Comment by bree-z** [comment]
Thanks, Boone!  This seems fine to me now.  :)

**Comment by boonebgorges** [comment]
Phew, thank you. Let us never speak of this again :-D https://github.com/cuny-academic-commons/cbox-openlab-core/commit/a708289d374e4962705f88d000d70ccd8fb3a249
