### ISSUE TITLE
Mobile "hamburger" site nav doesn't match non-mobile nav

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#159]
See #76.

The non-mobile main nav is built using a WP nav menu, which means that administrators can modify it in the Customizer and Dashboard > Appearance > Menus. The mobile version of this nav is not built using a WP nav menu. As such, while the two menus are identical by default, changes to the nav menu do not affect the mobile menu.

The mobile menu should probably be rewritten so that it's built using the nav menu data.

**Comment by bree-z** [comment]
This looks good, thanks!
