### ISSUE TITLE
Group Creation Steps/Edit Settings

### ISSUE THREAD

**Issue by jennaspevack** [cuny-academic-commons/openlab-theme#165]
Hi @samradd 
Do you want to take a quick look and compare the creation steps and edit settings subheadings? 

I think with the adjusting of the creation steps, we might need to have a closer look at the what each subheading is called in the Group Home > Settings.

I have some ideas, but wanted to run this by you first. 
:)

**Comment by samradd** [comment]
@jennaspevack Sorry that this one made it past me during my no-notifications stage.
Has this been addressed through other tickets or do you still have concerns?

**Comment by jennaspevack** [comment]
All good! Thanks @samradd
