### ISSUE TITLE
Course "last active" not being bumped by blog activity

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#167]
When I post or comment on a course site, it doesn't bump the course up on the homepage or group directories.  Joining a group, and other BuddyPress activity does immediately bring it to the top.  It's not an issue for other group types.  I also tried a hard refresh, but this didn't change anything.

See, for example: http://openlabdev.commonsinabox.org/groups/winter-appreciation/

The profile says Active 1 week, 2 days ago, but I posted today.  

<img width="900" alt="courseprofileactivity" src="https://user-images.githubusercontent.com/7189824/38816846-02b77e64-4165-11e8-83f5-aca9ddcd58fa.png">

<img width="670" alt="coursesiteactivity" src="https://user-images.githubusercontent.com/7189824/38816854-068f6556-4165-11e8-86ab-4721c42c708a.png">

**Comment by boonebgorges** [comment]
Really sorry about that, @bree-z - there was an error in the deployment script that caused the most recent changes from cbox-openlab-core not to be deployed to openlabdev.commons.gc.cuny.edu. This has been fixed and the changes deployed. I just checked at it appears that my fix is in fact working, but please have a look yourself.

**Comment by bree-z** [comment]
No problem.  :)  This looks good now, thanks!
