### ISSUE TITLE
Port accessibility changes from the OpenLab

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#168]
Those added in the last 12 months will need to be manually added. This is a generic ticket for collecting them.

**Comment by boonebgorges** [comment]
I've ported all the obviously relevant commits.

I've also done an initial WAVE scan of most main page types. Nearly all errors are gone. I have ignored contrast-related bits, as well as the empty h2 at the top of the right-hand nav for groups. For these items, see the discussion at #164.

I have made no attempt to bring over accessibilty-related changes for WordPress themes other than openlab-theme. These changes are, by and large, not appropriate for the CBOX-OL package to make, either because they're not reliable outside the OpenLab environment, or because it's more appropriate for the fix to go into the upstream product.

I'm going to close this ticket as resolved. If there are specific fixes related to what I've done (or have failed to do) here, let's handle them in standalone tickets.

**Comment by mkgold** [comment]
Thanks, Boone. Are there any accessibility features we can port over to CBOX Classic as well?

**Comment by boonebgorges** [comment]
@mkgold No features per se, but it's a good idea to do a review. I've opened https://github.com/cuny-academic-commons/commons-in-a-box/issues/134 to track it.

**Comment by mkgold** [comment]
awesome. thanks, Boone.
