### ISSUE TITLE
Course Cloning: New/Cloned course not copying data from source

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#171]
When cloning a course, most of the profile/home information and settings weren't copied correctly.  

Step 1:

- Description, Academic Units, Course Information (course code and section code) should have been pre-filled.
- Term should have been empty, but it was filled with the source course's information.  
- Course Privacy Settings weren't copied from source.

Step 2: 

- Site Privacy settings were not copied from source.

The site and all the appropriate content was copied successfully.

**Comment by boonebgorges** [comment]
Can you please give the precise steps behind "cloning a course"? When you say that details aren't being "copied", I think you mean that they're not being inserted properly into the creation form via the AJAX call, but there are multiple ways into this process, and I want to be sure I'm looking at the right thing.

**Comment by bree-z** [comment]
Sorry, Boone.  Yes, the data from the source course isn't being inserted properly into the creation form.  I still don't see the correct population of field values on the first step of cloning.  Here are some more details:

- Course I'm trying to clone: http://openlabdev.commonsinabox.org/groups/design-dev-test/
- Below is a screenshot of what I see during Step 1 of cloning.  
- Missing data: Description, Academic Units, Course Information
- Incorrect data: Term, Privacy Settings

![clonecoursestep1](https://user-images.githubusercontent.com/7189824/38888534-e98f2960-4249-11e8-8e5f-b0634235e450.png)

## Source Group Settings

![clonecourse_sourcesettings](https://user-images.githubusercontent.com/7189824/38888556-fe806870-4249-11e8-96a3-abbfc8daede0.png)

**Comment by boonebgorges** [comment]
Thanks very much for the additional details.

I've just tried cloning the same course that you're working with, and it worked for me. I'm wondering if perhaps your browser is stubbornly refusing to flush the cache for the JS file in question (this happens sometimes). Could you please load the file http://openlabdev.commonsinabox.org/wp-content/themes/openlab-theme/js/group-create.js?ver=4.9.5 in its own browser tab and do a hard refresh? Search the document for the text `academic-term` - if you see the following line, it means that you now have the up-to-date file:

    $('#academic-term').val(r.term);

Once you've done this, refresh the create page http://openlabdev.commonsinabox.org/groups/create/step/group-details/?group_type=course&clone=92 and see if things are working properly.

**Comment by bree-z** [comment]
That did the trick, thanks Boone!  Cloning worked as expected.

**Comment by boonebgorges** [comment]
Thanks for your patience!
