### ISSUE TITLE
DiRT messes up group creation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#174]
(for lack of a better technical term)

DiRT adds an extra step to group creation after Step 3/Invitations, which is a little strange:

- The confirmation message "created successfully" shouldn't appear here.
- The sub-heading says "Step One: [Group] Creation."  I'm not sure exactly what it should be - perhaps "Step Four: Enable DiRT"?

![dirt_groupcreation](https://user-images.githubusercontent.com/7189824/39017021-198b1582-43f0-11e8-8016-41749339c0c3.png)

**Comment by boonebgorges** [comment]
For the time being, we're not allowing any other plugins to intervene in the group creation process. It just so happens that the dirt-directory-client had found a way around this.

There is a more general discussion to be had about how much we're going to support non-CBOX plugins that add group creation/edit steps, but for the time being, I've made a change that should prevent dirt-directory-client from doing what it's doing.

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good.  I tested with all group types and with cloning.

**Comment by mkgold** [comment]
Hi Boone -- with this change, how would people find out about the existence of the DiRT tools tab? Only by going to Manage in the group navigation and noticing it is an option there?

**Comment by boonebgorges** [comment]
@mkgold Correct.

**Comment by mkgold** [comment]
Hmmm. That does not seem ideal. Is there anywhere else in the group creation process where we could logically add that enable/disable button?

**Comment by boonebgorges** [comment]
Not sure. Adding @jennaspevack @samradd

**Comment by boonebgorges** [comment]
I will create a toggle during group creation.

**Comment by mkgold** [comment]
thank you, Boone

**Comment by boonebgorges** [comment]
I've added the panel, just after Group Contact. If Braille is activated, those settings appear just after DiRT.

![screenshot_2018-05-10_16-11-31](https://user-images.githubusercontent.com/246627/39880285-dc8c1ec8-546c-11e8-8a43-1690269e37de.png)

If there are no further changes, this is ready for testing.

**Comment by mkgold** [comment]
That's awesome, Boone -- thank you. I feel like this is a great realization of what we promised in the proposal itself. Thank you

**Comment by moui72** [comment]
![DiRT](https://user-images.githubusercontent.com/3885628/39939193-6d3a8b60-5523-11e8-861a-e6e01a828e08.jpg)

**Comment by bree-z** [comment]
Thanks, Boone.  I tested out group creation with and without DiRT enabled, and enabling/disabling DiRT in settings, and that all works well.
