### ISSUE TITLE
Site URL error message doesn't indicate that uppercase can't be used

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#175]
When I create a site URL with uppercase letters, I get an error message that "URLs can contain only alphanumeric characters, hyphens, and underscores."  But, it doesn't indicate that characters must be lowercase.  

Can we force lowercase in the URL so that it will autocorrect if users use uppercase, but they won't see an error?  

Otherwise, we should add lowercase to the error message text.

Thanks!

<img width="886" alt="sitenameuppercase" src="https://user-images.githubusercontent.com/7189824/39440456-efd76920-4c78-11e8-9120-55c63dfefc7f.png">

**Comment by boonebgorges** [comment]
I've made the change so that URLs are forced to lowercase as you type. The new language from #141 also contains the 'lowercase' description.

**Comment by boonebgorges** [comment]
Sorry, I missed that this was the site URL page, not group URL. I've made the change.

**Comment by bree-z** [comment]
Thanks, Boone.  This looks good.
