### ISSUE TITLE
Admin Dashboard: Change Order of CBOX-OL Settings

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#176]
Hi Boone,

Can we change the order of the settings in the CBOX-OL section of the dashboard to the following?  

1. Plugins
2. Member Settings
3. Group Settings
4. Academic Units
5. Brand Settings
6. Communication Settings

Thanks!

cc: @charliemedwards

**Comment by boonebgorges** [comment]
I've changed the order.

Note that the first item 'Dashboard' - not listed here - cannot be easily removed. For technical reasons, WordPress needs the first item to point to the same location as the top-level item (CBOX: OpenLab).

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good.
