### ISSUE TITLE
Dashboard > CBOX-OL > Plugins: Add instructional text

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#177]
Hi Boone, 

We'd like to add instructional text to the Core and Member Site Plugins tabs in this section, to reflect similar instructions on the Community Plugins tab.

Add to Core Plugins tab:

"To update, check the plugins you want to update and click 'Update'."

Add to Member Site Plugins tab:

"To install, check the plugins you want to install and click 'Install'."

Thanks!

cc: @charliemedwards

**Comment by boonebgorges** [comment]
@r-a-y Could you please have a look?

**Comment by r-a-y** [comment]
Fixed in https://github.com/cuny-academic-commons/commons-in-a-box/commit/b526d5df0d17253baa00f95006235a8fa0e21aa1.
