### ISSUE TITLE
Stray Portfolio Profile links

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#178]
Charlie found a stray reference to the Portfolio Profile.  It appears in two places:

1. My Profile: Underneath My Portfoilo Site, there are links to 'Profile | Dashboard'
2. Viewing another user's profile: Underneath the Visit Portfolio Site link, there’s a link to Profile.  

I couldn't find mockups for this, so I wasn't sure if there's already design guidance.  If not, it seems to me that 'Portfolio Home' is more clear than 'Home', which I think could be confusing especially when viewing another user's profile.  

cc'ing Charlie and Jenna here too for thoughts.  @charliemedwards @jennaspevack 

Thanks!

<img width="1318" alt="portfolioprofilelink_anotheruser" src="https://user-images.githubusercontent.com/7189824/39543276-b81b8330-4e18-11e8-801a-e7324b8711d5.png">

<img width="1218" alt="portfolioprofilelink" src="https://user-images.githubusercontent.com/7189824/39543466-48f6f63c-4e19-11e8-8da0-694febfcb537.png">

**Comment by boonebgorges** [comment]
I've changed it to 'Portfolio Home'.

**Comment by bree-z** [comment]
Thanks, Boone!  Looks good.

**Comment by mkgold** [comment]
thanks, all.
