### ISSUE TITLE
Add bp-braille to package definition

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#183]
As soon as it's ready to be made a public repo.

**Comment by boonebgorges** [comment]
@r-a-y What's the best way to do this? `bp-braille` should be installed alongside `braille` - that is, installing one should install the other.

The bp-braille changes mean that the Braille plugin moves from `installonly` to `optional`, since it becomes a "community feature". Is it possible to just list Braille in the UI, but have it install both Braille and bp-braille?

**Comment by r-a-y** [comment]
> Is it possible to just list Braille in the UI, but have it install both Braille and bp-braille?

In theory, you'd need to add `braille` as a dependency plugin as well as adding a 'Depends` header for `bp-braille`.

But this might activate `braille` on the main site as a consequence when you install it via the "Member Site Plugins" tab in the CBOX-OL dashboard.  I might need to add a marker for dependency plugins so they are not auto-activated.

**Comment by boonebgorges** [comment]
Thanks, @r-a-y. Would you mind taking a first pass at this? The repo is https://github.com/hard-g/bp-braille.

To clarify, the behavior should be (I think): install (bp-)braille as an Optional item, at which point it's not *network* activated but instead is activated only on the main site; then, allow `braille` (but not `bp-braille`) to be optionally activated on secondary sites.

**Comment by r-a-y** [comment]
> To clarify, the behavior should be (I think): install (bp-)braille as an Optional item, at which point it's not network activated but instead is activated only on the main site; then, allow braille (but not bp-braille) to be optionally activated on secondary sites.

I've made this possible by introducing a new `'hide'` paramater when registering a plugin in CBOX - https://github.com/cuny-academic-commons/commons-in-a-box/commit/1733cc444f3ec9e50ec7c9723e36fe5035e465fc

The addition of `bp-braille` is done in this commit - https://github.com/cuny-academic-commons/commons-in-a-box/commit/ebf642f98ed14b23ad778610e5ff5d3c01080c70

@boonebgorges - Going to close this one, but let me know if you encounter any issues.

**Comment by boonebgorges** [comment]
Cool, I think this will work. Thank you!
