### ISSUE TITLE
Error on openlabdev.commonsinabox.org

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#185]
Hi Boone, 

Instead of the site homepage, I see a white screen with the following error:

Fatal error: Class 'HardG\BpBraille\Plugin' not found in /var/www/html/commons/openlabdev/wp-content/themes/openlab-theme/lib/plugin-hooks.php on line 475

Thanks!
Bree

**Comment by boonebgorges** [comment]
Sorry, I'd made the fix last week but didn't deploy to the testing site. I've made the change.

**Comment by bree-z** [comment]
It's up again, thanks!
