### ISSUE TITLE
Clicking Delete Account takes one to the public view of account page

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/openlab-theme#187]
I clicked "Delete Account" here but it just took me to a public view of the account

![screen shot 2018-05-16 at 11 02 15 am](https://user-images.githubusercontent.com/278503/40125346-b21ea760-58f8-11e8-9510-f411fb5082a1.png)

**Comment by bree-z** [comment]
I don't see the ability to delete the super admin account, and when I'm logged in as a non-admin, clicking delete account works as expected.
