### ISSUE TITLE
Questions about profile page

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/openlab-theme#188]
Sorry to leave multiple questions here, which may have been answered elsewhere. Or it may be too late to address them if there are issues. but I wanted to ask:

1. there seems to be duplication between the horizontal and vertical menu items for profile editing. The "Account Settings" link on the horizontal menu appears to take one to the same place that "My Settings" does on the right-hand vertical nav. Do we need both? I would argue for removing "My Settings" from the vertical nav, because most of the account settings links seem otherwise to be located in the horizontal nav

2. Why does "Create Portfolio" appear under My Profile -- but not "Create Course" or any other kind of content? What happens if the admin of a CBOX-OL site deletes the "Portfolio" group type?

![screen shot 2018-05-16 at 11 03 46 am](https://user-images.githubusercontent.com/278503/40125631-5d1ad9ea-58f9-11e8-87b2-1ac9707edc59.png)

**Comment by moui72** [comment]
@mkgold I am not Boone, but I think I can mostly answer these questions. Apologies if my knowledge is inaccurate for CBOX-OL. I am mostly answer out of experience with the OpenLab.

1. The sidebar "My Settings" brings you to the "My Settings" section. The top nav is the subsection navigation for this section, and the "Account Settings" for this nav brings you back to the landing page for the section. That is, the links are not quite redundant, and it would perhaps be counterintuitive to have to use the sidebar link to return to the landing page. I think both links have merit; it might be more intuitive, though, if "Account Settings" were instead called "Settings Home" or something of the like. 
  + The sidebar is for navigating between sections of the profile. The sidebar link allows you to access the settings section from anywhere in the profile area.
  + The top link allows you to return to the landing page of the settings section without the potentially unintuitive step of re-navigating to the same section you are in.


2. On the OpenLab, portfolios are different than other group types. A user can have only one associated with their account, and it is featured on their profile more prominently than other group types. A user can have any number of courses/projects/etc. As for the interaction with CBOX-OL customization, I think @boonebgorges will have to answer that.

**Comment by boonebgorges** [comment]
> there seems to be duplication between the horizontal and vertical menu items for profile editing. The "Account Settings" link on the horizontal menu appears to take one to the same place that "My Settings" does on the right-hand vertical nav. Do we need both? I would argue for removing "My Settings" from the vertical nav, because most of the account settings links seem otherwise to be located in the horizontal nav

I'd suggest that it's too late to make any change of this sort, which would probably require lengthy discussion. Cc @jennaspevack @bree-z @samradd 

> Why does "Create Portfolio" appear under My Profile -- but not "Create Course" or any other kind of content?

Portfolios a special group type that is linked with users, such that each user has the opportunity to create a single portfolio.

> What happens if the admin of a CBOX-OL site deletes the "Portfolio" group type?

The item does not appear.

**Comment by bree-z** [comment]
Just to echo what @moui72 has said, I don't see "My Settings" in the sidebar/vertical nav as redundant because if you don't click this link in the sidebar, you won't get to see the horizontal subsection nav.  

I'm in favor of leaving both links.  :)

**Comment by boonebgorges** [comment]
Tentatively closing. @mkgold and others, if it seems like we need more discussion here, please reopen with thoughts.
