### ISSUE TITLE
Awkward Friendship Cancellation message

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/openlab-theme#189]
Under Profile > My Friends, the cancel friendship link reads "cancel friend," which is a bit awkward. Maybe "cancel friendship" or just "cancel"?

![screen shot 2018-05-16 at 11 08 15 am](https://user-images.githubusercontent.com/278503/40125723-96765ab6-58f9-11e8-9693-30fb41acf93e.png)

**Comment by boonebgorges** [comment]
Please, someone give me the language and I will make the change.

**Comment by moui72** [comment]
@boonebgorges is the functionality of this to cancel a friendship request or to cancel an existing friend relationship?

Here are my suggestions:

For pending friendship requests: "Cancel request"
For canceling existing friendship: "Drop friend" (or "Unfriend")

**Comment by boonebgorges** [comment]
Copying from https://github.com/cuny-academic-commons/openlab-theme/issues/166#issuecomment-389574015:

> We use "cancel friendship" on the Commons and I think that's fine

**Comment by boonebgorges** [comment]
I've made the change and deployed to openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
This looks good.  I see "Cancel friendship" now when I hover over the button.

**Comment by mkgold** [comment]
thanks!
