### ISSUE TITLE
Sending an invitation leads to "You haven't sent any email invitations yet" message

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/openlab-theme#190]
Are email invites working on the dev site? I sent an invitation but it did not appear to go out. After it was sent, I was taken back to the invitation screen which said "You haven't sent any email invitations yet"

**Comment by boonebgorges** [comment]
Can you please give detailed instructions to reproduce?

**Comment by bree-z** [comment]
I was just able to reproduce this.  Group invitations are working fine.  But, invitations to join the platform are not.  Here's what I did:

- I went to My Profile > My Invitations > Invite New Members (http://openlabdev.commonsinabox.org/members/testfaculty/invite-anyone/)
- I entered work@bree.bz (bree.bz is a whitelisted email domain).  
- After I click "Send Invites", I end up on the Sent Invitations page, and see a message that "You haven't sent any email invitations yet." (http://openlabdev.commonsinabox.org/members/testfaculty/invite-anyone/sent-invites/send/) 

![screen shot 2018-05-17 at 3 42 44 pm](https://user-images.githubusercontent.com/7189824/40199965-0cae2232-59e9-11e8-917c-1cf1d975dbca.png)

**Comment by boonebgorges** [comment]
Thanks very much for the confirmation and details, @bree-z. We fixed this previously on the OpenLab: http://redmine.citytech.cuny.edu/issues/2181

I've just pushed up a fix to openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks, Boone.  This looks good to me!

**Comment by boonebgorges** [comment]
Thanks!
