### ISSUE TITLE
Home page columns should accommodate < 4 group types

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#192]
From @charliemedwards 

> Hmmm… I thought that the home page was going to adjust according to how many group types you have enabled. I disabled clubs and there’s now a hole in it… :) It will look pretty weird for people who are just using one group type. Is it possible to address this?? Or am I misunderstanding something? (Note: I think this was the biggest thing that came up…)

This was discussed at one point but not described in the spec, which I guess is why it wasn't built. 

Major overhauls are not possible at this point. We may be able to introduce some minor changes that expand the column width for 3 group types. 2 group types gets pretty distorted. Some naive screenshots are attached - they are broken in various ways, but they give you the idea of what happens.

![screenshot_2018-05-21_14-38-39](https://user-images.githubusercontent.com/246627/40313313-eda2d828-5d04-11e8-8e7a-fe9bd36b1fcf.png)
![screenshot_2018-05-21_14-39-49](https://user-images.githubusercontent.com/246627/40313314-edb7ebf0-5d04-11e8-8e9c-f6aeb309c699.png)

So, my suggestion is that, with *3 group types or fewer*, the columns are converted to `col-sm-8` (one-third width); going any wider is going to require more design work. I'd like to get some sort of word one way or another from @jennaspevack before moving forward with the technical work that would be required to make this work.

**Comment by charliemedwards** [comment]
Thanks so much, Boone! This may not be possible/make sense, but just in case it helps: for 2 or fewer group types, would it be possible just to load more of them into the existing four column layout??? i.e. if two group types, they would display in two columns each, and if one group type, all four columns would be used???

**Comment by boonebgorges** [comment]
@charliemedwards That is an interesting idea, but is not possible at this time. If you'd like to pursue the idea in a future release, it should probably be recorded outside of this ticket; here, we should focus on what can be done under the current scope.

**Comment by boonebgorges** [comment]
Here are screenshots of what happens with 3 and 2, under my proposal:

![screenshot_2018-05-23_17-53-23](https://user-images.githubusercontent.com/246627/40442135-63a2192c-5eb2-11e8-874e-a8eef1f84f56.png)
![screenshot_2018-05-23_17-53-01](https://user-images.githubusercontent.com/246627/40442136-63b4faba-5eb2-11e8-8ba4-2bf2e727d1f2.png)

cc @jennaspevack @charliemedwards

**Comment by jennaspevack** [comment]
@boonebgorges Thanks! This seems good for now. I'll open another ticket with some ideas for improved layout down the road.

**Comment by mkgold** [comment]
I think this is a great solution. thanks so much, Boone.

**Comment by boonebgorges** [comment]
Thanks, all.

**Comment by bree-z** [comment]
Hi Boone -- I see the testing label, but has this been implemented yet?  I don't see any changes.   
Thanks!

<img width="1217" alt="clubsturnedoff" src="https://user-images.githubusercontent.com/7189824/40652711-ac86e22e-6341-11e8-8ef4-fd6a06cfc61f.png">

**Comment by boonebgorges** [comment]
Hi Bree - Yes, it's implemented. You've got to actually disable the Clubs widget to test (not just delete all clubs). Dashboard > Appearance > Widgets

**Comment by bree-z** [comment]
Ah, ok, thanks!  I just turned off the group type.  This looks good after I disable one (or two) widgets.

**Comment by mkgold** [comment]
Great! Thanks for your work, @boonebgorges and thanks for your intensive testing @bree-z !
