### ISSUE TITLE
Abstract 'Join OpenLab' language in sign-in widget

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#193]
From @charliemedwards 

> Reference to “Join OpenLab” <- should be either configurable or generic (e.g. Sign Up would be consistent with terminology used in top menu)

**Comment by boonebgorges** [comment]
![screenshot_2018-05-21_16-41-40](https://user-images.githubusercontent.com/246627/40318940-d968ac28-5d15-11e8-924d-1f16abf4517c.png)

Changed to 'Sign Up'.

**Comment by bree-z** [comment]
Looks good, thanks!
