### ISSUE TITLE
Rerender default logo

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#194]
From @charliemedwards 

> Unless there’s something wrong with my eyes, the logos in both header and footer look fuzzy
> Is it possible to use the non-tagline version of the logo in the header, as it’s not readable there?

See #140 

Will rerender from vector once I have the logos. @jennaspevack - I am working from https://www.dropbox.com/sh/3ok9zru1eos7mn1/AACScnmemlWZEX6Vdyz8au5Na?dl=0 but I don't see a version without the tagline. Do you have a more complete set of logo assets to share with me?

**Comment by jennaspevack** [comment]
@boonebgorges @charliemedwards 

All versions are in cboxol-branding-finalV2.pdf, but here is an ai file with each in a separate artboard, if that works better. I'm happy to save out individual files too, just let me know.
https://www.dropbox.com/s/fglv34ueqtzsv6h/cboxol-finalV3.ai?dl=0

**Comment by boonebgorges** [comment]
@jennaspevack Would you mind separating out the items that I need into pngs? I am not smart with .ai files and I don't want to wreck anything.

**Comment by jennaspevack** [comment]
Sure thing. 

And here is a folder of pngs:
https://www.dropbox.com/sh/go9sgf3vdnprlnh/AACOrStZr3UhF4e00-iNJ7xNa?dl=0

**Comment by jennaspevack** [comment]
Here is a folder of all in eps (in case you need to resize):
https://www.dropbox.com/sh/w2b1975na8ayz29/AADm4p9C_iZYSFVcf0E8V1pua?dl=0

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack ! This is great. (Related: Could we have some sort of definitive styleguide? Something as simple as a Google doc that links to all the "official" logos.)

I've made the change to the default site logo.

@r-a-y Can you ensure that the logo on the CBOX-OL dashboard panel is sufficiently rendered, replacing with the linked item if necessary?

**Comment by r-a-y** [comment]
I've re-rendered the OL logo for the dashboard here - https://github.com/cuny-academic-commons/commons-in-a-box/commit/0d2f024769c1ac7d99d80e59c6f831867f178c8d

**Comment by boonebgorges** [comment]
Cool, I think this one is done.
