### ISSUE TITLE
Change group privacy text

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#197]
from @charliemedwards 
![screenshot_2018-05-21_14-57-38](https://user-images.githubusercontent.com/246627/40314212-5acdf91c-5d07-11e8-8b01-5a37ce8660b5.png)

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by bree-z** [comment]
This looks good.  I tested for all group types.
