### ISSUE TITLE
Change site privacy settings text

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#198]
From @charliemedwards 

![screenshot_2018-05-21_14-58-26](https://user-images.githubusercontent.com/246627/40314244-754c3902-5d07-11e8-90d4-5c31060bef9a.png)

**Comment by boonebgorges** [comment]
I've made the your/the and administrative/administrator changes.

Changing to "members of this project" will mean rebuilding much of the logic on this page, and adding another string. I'm setting it aside for the moment. If there's time after processing the most recent influx of issues, maybe we can reassess.

Wasn't sure whether to take action on the sidebar comments. If anyone wants to chime in with specific instructions, I can make the changes.

**Comment by bree-z** [comment]
I wasn't sure about the first and last sidebar comments.  Regarding the middle comment about the text "Note: These options will NOT block access to the site. It is up to search engines to honor your request."

Technically it's true that blocking access only refers to the second option.  What if we just say something like: 

"Note: Blocking search engines is not guaranteed.  It is up to them to honor your request."

**Comment by boonebgorges** [comment]
Thanks, @bree-z. If it's specific to the second option, maybe we should just remove the Note, and add the clarificatory text to the second option.

**Comment by jennaspevack** [comment]
I was working on some layout and typography changes for OL recently and came across this same issue. Here's a mockup with similar changes to the location of that note. Maybe something like this?
![ctol_courseprofile-admin-reorder oer-cbox](https://user-images.githubusercontent.com/22797200/41111661-99d0b4c4-6a4a-11e8-8a5c-7ca38e420b54.png)

**Comment by bree-z** [comment]
Looks good, in group creation and settings.  Thanks!
