### ISSUE TITLE
Don't say 'Group Forum' on single topic button

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#199]
From @charliemedwards 

![screenshot_2018-05-21_15-00-33](https://user-images.githubusercontent.com/246627/40314356-ca5244be-5d07-11e8-830e-b8b59455e2a2.png)

**Comment by boonebgorges** [comment]
I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks!
