### ISSUE TITLE
Text mods to 'Invite New Members'

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#200]
From @charliemedwards 

![screenshot_2018-05-21_15-02-42](https://user-images.githubusercontent.com/246627/40314459-0ef612c6-5d08-11e8-9eb1-95f0f07ab439.png)

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by bree-z** [comment]
This looks good, thanks!
