### ISSUE TITLE
Contact Us form not properly configured

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#203]
From @charliemedwards 

![screenshot_2018-05-21_15-06-10](https://user-images.githubusercontent.com/246627/40314642-97a05500-5d08-11e8-9945-479144d17368.png)

I'm not sure why the page on openlabdev.commonsinabox.org looks like that. The default text of the Contact Us page is: "This is the content of your Contact Us page". @bree-z Did you begin some configuration of this page? In any case, it's not possible for us to set up default configuration for contact forms, both because of the late date and because of the complexity (what would the default form say? who would messages go to? what plugin would be used?). At best, we can add links to the default content that go to some external documentation.

**Comment by bree-z** [comment]
I didn't begin any configuration of this page, but @vothsco might have?

**Comment by boonebgorges** [comment]
Ack, I discovered that the theme does this. I've removed it.
