### ISSUE TITLE
Scroll weirdness on Plugins panel

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#205]
From @charliemedwards 

![screenshot_2018-05-21_15-12-32](https://user-images.githubusercontent.com/246627/40314907-6ecdb70c-5d09-11e8-9dfd-c9ecf95256e5.png)

**Comment by r-a-y** [comment]
This is to do with the custom toolbar and isn't specific to the Plugins page.

@boonebgorges - I can take a look, but do you want first dibs on this?

**Comment by boonebgorges** [comment]
@r-a-y Would you mind spending a couple minutes first? If it's not fairly obvious, feel free to pass it back. (I am swamped)

**Comment by boonebgorges** [comment]
Thanks, @r-a-y. Yes, it would make sense to prevent the adminmenu from doing this, but I don't know the source of the behavior. It seems to happen only on cboxol pages.

I don't have the time to dig, so I wrote a terrible little function that adjusts `top`. It's not completely smooth, but it prevents overlap.

**Comment by bree-z** [comment]
Looks good, thanks!

**Comment by charliemedwards** [comment]
Hey there - I'm still seeing the issue in some cases (wondering if it's fixed on pages where the content extends below the fold and not on ones where it doesn't???) - e.g. in Member Settings, Member Types and Profile Fields still had a problem when I scrolled down the page and back up again (as you might if you were looking for something in the left-hand menu), but Registration seemed to be OK (Firefox on Windows 7)...

**Comment by boonebgorges** [comment]
I've just pushed up a more general attempt to work around the issue. As before, it's not a proper fix, but it should prevent overlap. It's not possible to reengineer it completely at this point.

**Comment by charliemedwards** [comment]
Thanks, Boone - that's better, though I'm not able to scroll down the page. Presumably I'd only be doing that if I wanted to look at/do something using the lower reaches of the left-hand menu, so not a huge thing, but let's not lose track of fixing it properly. :)

**Comment by boonebgorges** [comment]
Closing in favor of https://github.com/cuny-academic-commons/commons-in-a-box/issues/175
