### ISSUE TITLE
Inline help text about what happens when disabling group/member type

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#206]
From @charliemedwards 

> Could we add some text to explain what happens when you turn the member type off?

Will need design + text.

**Comment by jennaspevack** [comment]
@charliemedwards, I'm not exactly sure what happens when member type is turned off. @bree-z, is this something you've tested and do you have suggestions about language to explain? I think we could just add a line next to the on/off toggle.

**Comment by boonebgorges** [comment]
Closing out the milestone - if this is still an issue, let's open a public ticket at https://github.com/cuny-academic-commons/commons-in-a-box/issues
