### ISSUE TITLE
Don't allow empty space on group filter sidebar

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#210]
From @jennaspevack. See https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAAdCNK5uoY12DyhU6v5s5zra?dl=0&preview=1filter-proximitytosubmitbutton.png

This must happen when filters are disabled for the type. I don't know off the top of my head whether this is easily fixed but I will look.

**Comment by bree-z** [comment]
This looks good, thanks!  I also tried disabling some filters and the spacing was fine.
