### ISSUE TITLE
Notification and other count bubble styling

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#212]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AADXnkptwX4vfLMiUtqkuotEa/AlertChanges.png?dl=0

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by jennaspevack** [comment]
Thanks @boonebgorges Still seeing the Notification messages in white.
![image](https://user-images.githubusercontent.com/22797200/40559040-65490e1c-6023-11e8-830d-ced1bba8a85c.png)

**Comment by boonebgorges** [comment]
@jennaspevack Can you point out the notification you're talking about? Is it `Membership`? My understanding was that this is a different count type - it's related to a "passive" count rather than a "new/unread" count.

**Comment by jennaspevack** [comment]
It's the pink bar with white text "Group settings were successfully updated". All Notifications/Indicators (under the avatar, settings, etc and the little circles). Sorry that wasn't clear. It was number 8 on the original AAA update- somehow I missed it.

**Comment by boonebgorges** [comment]
Oh, gotcha. I thought the ticket was just for the count icons. I'll make the change.

**Comment by boonebgorges** [comment]
Notification color has been change.

**Comment by bree-z** [comment]
This looks good to me.  I tested most notifications, though not sure if I found every single one to test.  Count icons also look good.
