### ISSUE TITLE
Styling mods to group create screen

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#213]
from @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAABH7yt8MdPdcD0m_19tqq4a/Create%3Aclone%3Estep1.png?dl=0

**Comment by boonebgorges** [comment]
page 2 https://www.dropbox.com/sh/i9krg6tdk1mzebq/AACg2SJnbNkzg6Na4Y24Oekla/Create%3Aclone%3Estep2.png?dl=0

**Comment by boonebgorges** [comment]
Reference for original `.radio` margin:

https://github.com/livinglab/openlab/commit/189e788019bedbbf31cb0ee3676e8fc38ebaa736
http://redmine.citytech.cuny.edu/issues/1865

I've rolled it out.

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by bree-z** [comment]
These changes all look OK visually and I double checked with the web developer extension.
