### ISSUE TITLE
Group > DiRT appearance mods

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#214]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AABC-H1SfMRLJhvmUF8BR7V2a/Dirttools-GroupHome.png?dl=0

I'll review each of these separate, as I'm unsure how hard they will be to implement technically.

**Comment by boonebgorges** [comment]
I've made a number of the changes.

I'm not 100% sure I understood the "Remove this copy" part. My interpretation was that you should see the following when the group has no tools in use by its members:

![screenshot_2018-05-21_21-00-21](https://user-images.githubusercontent.com/246627/40338326-15b492a4-5d3a-11e8-8cfe-0a39152dda62.png)

and the following when the group's members do have tools:

![screenshot_2018-05-21_21-00-06](https://user-images.githubusercontent.com/246627/40338334-1cb5fa5c-5d3a-11e8-94b7-f983de94506e.png)

I also don't fully understand the `entry-content` comment. For one thing, the items are already in `entry-content`. For another, it's not clear to me that `entry-content` does much/any styling of typography and layout.

@jennaspevack Could you please have a look and let me know where I've gone wrong?

**Comment by jennaspevack** [comment]
Yes, this looks good. Thanks!

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack ! Since things are not looking good for DiRT, let's spare @bree-z the work of thorough testing.
