### ISSUE TITLE
Remove extraneous text on single forum thread screen

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#215]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAAUx0gTYr6Xe-AJyeflTi0wa/discussion-subscribebutton.png?dl=0

These need a review for feasibility, and may be pushed from this release.

**Comment by boonebgorges** [comment]
See also https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAAdSuKwet2X72COZir0FYfXa/discussionbugs2.png?dl=0

**Comment by boonebgorges** [comment]
I've made most of the changes.

![screenshot_2018-05-21_21-30-35](https://user-images.githubusercontent.com/246627/40339064-3a40dd54-5d3e-11e8-8b34-1ca61d889a66.png)

I have no idea what the Subscribe button does. The fact that it shows up only for non-group-members makes me think it shouldn't be there. @bree-z Can you please give us your expert view here?

**Comment by bree-z** [comment]
We don't have the subscribe button on the OpenLab, for logged-in or non-logged in members.

**Comment by bree-z** [comment]
Oh, wait, sorry, I misunderstood!  I was looking at logged-in and not, but for logged-in *non-members* of a group it does appear on the OpenLab.  It allows them to subscribe to email updates to a forum topic in a group they're not a member of.  I'm guessing it's not a widely-used piece of functionality but it's there.  

Also, @jennaspevack , do you want me to put in a ticket for the changes you specify above (e.g. remove header, and extra text) on the OpenLab as well?  

thanks!

**Comment by jennaspevack** [comment]
@bree-z Yes please! Thank you!

**Comment by bree-z** [comment]
Sorry, forgot to say above that all changes look good to me.

Not sure if we're keeping the subscribe button since it mirrors OpenLab functionality, but everything else looks good, thanks!

**Comment by boonebgorges** [comment]
At this late date, let's leave Subscribe and call this ticket fixed.
