### ISSUE TITLE
Docs empty language change

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#216]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAD_Pnx4XcTUcgIfd10Bhd-Wa/Docs-language-change.png?dl=0

Will do a feasibility review.

**Comment by boonebgorges** [comment]
We already had the template so this was a straightforward change.

**Comment by bree-z** [comment]
Looks good, thanks!
