### ISSUE TITLE
Remove BPGES status from group header

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#217]
From @charliemedwards and @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AADwT-Fuc6klLahbcw2ESrYza/emailstatus-removefromGroupHome.png?dl=0

**Comment by boonebgorges** [comment]
Fixed.

**Comment by bree-z** [comment]
Looks good, thanks!
