### ISSUE TITLE
Language changes for Files

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#218]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AADh5RYVp_1O87qCuFfF86NTa/files-language-change.png?dl=0

Will do a feasibility review.

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by bree-z** [comment]
Thanks, this looks good!

Just one question: there are a number of other places where the word 'document' appears.  Do we also want to change to 'file'?  They are, when logged in as a group member:

1. Upload a New Document button
2. Upload a New Document form
2a. Featured Document checkbox
3. Document Uploaded confirmation

<img width="630" alt="1uploadnewdocumentbutton" src="https://user-images.githubusercontent.com/7189824/40493407-5798d8c2-5f7b-11e8-9e1d-0f7ccec37f23.png">

<img width="868" alt="2uploadnewdocumentform" src="https://user-images.githubusercontent.com/7189824/40493408-57bde6bc-5f7b-11e8-9a07-d37e7a944345.png">

<img width="876" alt="3uploadconfirmation" src="https://user-images.githubusercontent.com/7189824/40493410-57eaf120-5f7b-11e8-9b75-410bac77c3ba.png">

**Comment by jennaspevack** [comment]
Thanks Bree! Yes, I think changing language from Document to File would make sense.

**Comment by boonebgorges** [comment]
Sounds good. I've made the change in each place noted by Bree.

**Comment by bree-z** [comment]
This looks good, thanks!
