### ISSUE TITLE
Group sidebar styling mods

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#225]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AAAdCNK5uoY12DyhU6v5s5zra?dl=0&preview=ProjectHomeNoSite-alignment.png

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by boonebgorges** [comment]
Thanks, Bree. The issue here wasn't courses vs other group types, it was that the group had a course, but the course wasn't visible to the current viewer, so that the Course Site section was being rendered as an empty box. I've made some mods to account for this case.

**Comment by bree-z** [comment]
Ok, thanks.  And this looks good!
