### ISSUE TITLE
Styling changes on group directories

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#226]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AACpGDNHHKVznQY9JpaeiIzSa/ResultsPages-alignmentafterfilter.png?dl=0

**Comment by boonebgorges** [comment]
This should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
