### ISSUE TITLE
Search dropdown styling

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#227]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AABm34k2JhJouCVOwgiiGHOHa/seachdropdown-needsdesign.png?dl=0

**Comment by jennaspevack** [comment]
@boonebgorges I realize now that the difference with this design is just the addition of the extra text. I'm not sure why the extra text was added, but it makes the functionality more confusing. Can we just keep what's on the OpenLab currently- ie: remove the extra text?
![image](https://user-images.githubusercontent.com/22797200/40494291-7f2bfed4-5f42-11e8-9380-cf52af9a85e5.png)
![image](https://user-images.githubusercontent.com/22797200/40494369-b0382a02-5f42-11e8-963f-d8fc39c25a3d.png)

**Comment by bree-z** [comment]
Looks good, thanks!
