### ISSUE TITLE
Styling changes to profile edit

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#228]
From @jennaspevack 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AADVGZhY-XVJtYmQEfsPBGOaa/Settings%3EPrivacySettings-.png?dl=0

**Comment by boonebgorges** [comment]
Regarding "Remove Details" - This change was part of the group redesign and reorg spec, and I think it's meant to differentiate between the first panel and the 'Settings' panel. cc @samradd

**Comment by boonebgorges** [comment]
All other changes are ready to test.

**Comment by samradd** [comment]
Yes, "details" was included to differentiate this section from the other settings.  Given the group-language decisions we've made, I'm open to changing it to just '[Group Type]' if reducing words is desired.

**Comment by bree-z** [comment]
All changes look good to me, thanks!
