### ISSUE TITLE
Sidebar on Terms and Contact Us

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#230]
From @jennaspevack and @charliemedwards 

https://www.dropbox.com/sh/i9krg6tdk1mzebq/AACIUoObtbp6FqK6KK7jWuhia/TermsContact-nosidebar.png?dl=0

I'm unsure what this sidebar should be. Can I get some help?

**Comment by boonebgorges** [comment]
(Moving out of Beta milestone on the assumption that this was something overlooked in the spec; it's too late to bring in additional stuff from the OpenLab. But if I'm misunderstanding, or there's an easy fix, we can move back.)

**Comment by jennaspevack** [comment]
I believe it's an easy fix. :) Terms of Use and Contact Us are children of About (main nav). The sidebar for About should be added to these two pages for navigational consistency.

**Comment by jennaspevack** [comment]
See OL for reference:
https://openlab.citytech.cuny.edu/about/

**Comment by boonebgorges** [comment]
This did turn out to be fairly easy. Ready for testing.

**Comment by bree-z** [comment]
Looks good, thanks!
