### ISSUE TITLE
Default content/setup for group type templates

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#232]
@charliemedwards noted in her recent review that [ Group Home ] links were not working for all group types. As @bree-z surmised, this is related to the nature of the template: it's likely that only the Course template had been set up, or at least set up with a menu dedicated to the Primary Menu section.

As part of the installation routine, we will have to set up some bare minimum amount of configuration for group type templates. The very barest minimum would be the creation of a menu that's located in the Primary Menu theme location, as this is what's required to have the Group Home menu appear across themes. But it can also include:

- default theme
- a handful of default pages with dummy content ("Syllabus")
- other menu items

Not sure how this didn't get done earlier, but it needs doing now. Could I ask @bree-z or another member of the team to make a draft? For each group type, what should the default theme be, should there be any default pages, and should there be anything in the default menu other than the [ Group Home ] and Home links?

**Comment by jennaspevack** [comment]
@boonebgorges I think I was supposed to do this. 

Can I set these up directly in the current templates? For example:
http://openlabdev.commonsinabox.org/site-template-portfolio-1527098856/

**Comment by boonebgorges** [comment]
@jennaspevack Sure thing, but please give me a heads-up when you're going to do it. When I have to run the reinstallation routine on openlabdev.commonsinabox.org (which is fairly frequent when we introduce new strings, etc), it wipes these templates and recreates them. If you're planning on doing it soonish, I'll hold off on any erasure until I hear from you that you're done. Thanks!

**Comment by boonebgorges** [comment]
One more thing - I am going to have to translate the state of the template site as you've set it up into a set of programmatic instructions for configuring the default, so if you could give a brief summary of the things you changed, it would help me ensure that I haven't missed anything. Could be as simple as "changed theme, added a menu, added Pages" or something like that - just enough so I know where to look in the Dashboard for the config you've done.

**Comment by jennaspevack** [comment]
I'll plan to do this tomorrow night, but I can also just make the list of changes with some screenshots, so you're not waiting on me.

**Comment by boonebgorges** [comment]
If it's not too much extra work to make the list (screenshots optional but nice; hopefully you're not making mods that are so complex they need huge amounts of visual explanation!!), it would help me a huge amount. Then yes, once that's done, I don't need the live sites anymore.

**Comment by jennaspevack** [comment]
No, not too complex, I hope. :) Bree, Charlie and I thought we could just follow the OL templates more or less. Is having content like what we have on the ePortfolio Template, for example, considered too much? If so, I'll simply.

**Comment by boonebgorges** [comment]
Setting up widgets, in particular, gets fussy and complicated, so it would be nice if those were kept to a minimum. (Lots of them that are relevant on the OpenLab are not relevant for this package.) But do whatever you think is appropriate, and I'll see what can be done on my end.

**Comment by jennaspevack** [comment]
@boonebgorges I updated the following templates:
http://openlabdev.commonsinabox.org/site-template-club-1527098857/
http://openlabdev.commonsinabox.org/site-template-project-1527098858/
http://openlabdev.commonsinabox.org/site-template-course-1527098855/
http://openlabdev.commonsinabox.org/site-template-portfolio-1527098856/

Here's the [list](https://www.dropbox.com/s/8c1xzmgsgf3opse/Template%20Changes.rtf?dl=0) of changes for each.

Let me know if anything needs clarification. :)

**Comment by boonebgorges** [comment]
Thanks, Jenna. I've made the changes. Here are the new sites:
http://openlabdev.commonsinabox.org/site-template-course-1527613551/
http://openlabdev.commonsinabox.org/site-template-portfolio-1527613553/
http://openlabdev.commonsinabox.org/site-template-club-1527613554/
http://openlabdev.commonsinabox.org/site-template-project-1527613555/

(Old sites are still there for reference.)

A few notes:

1. For Club and Project, you said to keep the Sample Page page. For Course and Portfolio, you said to add other pages, but didn't specifically say whether to keep the Sample Page page. I've kept it. (It only appears in the menu on Club and Project, as per the spec.)
2. In the Dropbox document, you said Resume (Portfolio template) was a child of Academics. Your sample site had it as a child of Career, which I think is what you meant. I went with Career in the actual build.
3. The text of Career and Academics (Portfolio template) has links to the subpages Sample Course and Resume. Creating these links makes the installation setup routine much more complex to build and much slower to run (since the parent text has to be updated after the child page is created), so I've left the links out. See http://openlabdev.commonsinabox.org/site-template-portfolio-1527613553/career/.
4. You asked about the "Tagline". This happens automatically based on the name of the WordPress network, so if someone calls it the "Foo Commons", the site tagline will be "Just another Foo Commons site."
5. You specified "All templates should include link back to "Group" Home." These links appear only (and automatically) for actual sites that are linked to groups. The templates are not linked to groups, so they don't appear. To verify, create a Club site (etc) and you should see the link.
6. You didn't specify a 'Home' link for the menu, but the Home link is dynamically added as part of the original port from the OpenLab. As such, I've left it there. Let me know if it should be removed.

@jennaspevack Let me know if you have further action items for me based on the above, before handing off to Bree. Thanks!

**Comment by jennaspevack** [comment]
Looks good to me! Thanks!

**Comment by boonebgorges** [comment]
Fantastic - thank you!

Bree, I'm not sure what needs testing here right at the moment, given that Jenna and I have both had a look. Perhaps this can wait until such time as we do any installation testing. I'll leave the label off of it for the moment.

**Comment by boonebgorges** [comment]
Not sure how we'll test this further, so I'll mark as resolved.
