### ISSUE TITLE
Add clarifying copy in Dashboard>Group Types

### ISSUE THREAD

**Issue by jennaspevack** [cuny-academic-commons/openlab-theme#234]
This may not be possible for Beta, but I just realized that once Courses and Portfolios are renamed in Group Settings:Types there is no way to show that they each have unique functionality and appearance that differs from other group types.

Can we add a line of copy that clarifies the original group type for Courses and Portfolios?
https://www.dropbox.com/s/02deg8ankxhrqlz/DashboardGroupSettingsTextCoursesType.png?dl=0
https://www.dropbox.com/s/j6uatsc01i1v72c/DashboardGroupSettingsTextPortfolioType.png?dl=0

**Comment by boonebgorges** [comment]
This is ready to test.

**Comment by bree-z** [comment]
Looks good, thanks!
