### ISSUE TITLE
Support for message starring is mostly incomplete

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#236]
Several versions ago, BuddyPress added the ability to "star" private messages. The OpenLab's message templates were forked from BP's before that, and the new functionality was never merged in. But in one place, the star functionality does leak through a bit: the message HTML that's returned via AJAX directly after posting a reply to a thread. (This bit of markup is generated by BP, rather than by our theme.)

![screenshot_2018-05-25_14-55-48](https://user-images.githubusercontent.com/246627/40551180-c577d0cc-602b-11e8-8cce-ea2b3bc51b3e.png)

In the future, we may want to support starring, but for the moment, my recommendation is to hide this one bit of interface with CSS. We can do this much for the beta release, but no more. @jennaspevack @bree-z Does this sound OK to you?

see #235

**Comment by bree-z** [comment]
Makes sense to me to hide it for the beta release.

**Comment by jennaspevack** [comment]
Yes, sounds good.

**Comment by boonebgorges** [comment]
Thanks to both of you. I've made the change.

**Comment by bree-z** [comment]
This looks good to me, thanks!
