### ISSUE TITLE
URL Change for Group Profile Mobile Issue

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#246]
A little hard to explain and maybe inconsequential but:

In step 1 of the group creation process, the box "URL (required) auto-populates from the group name. On mobile, you can't see what the actual name is because the box is too small: 
![img_2706](https://user-images.githubusercontent.com/11300891/43007876-9f69e3d6-8c07-11e8-9f46-0eafd4651316.PNG)

If you attempt to edit the url, no text shows but you can still edit it. This seems like a general usability problem but how many people a) create groups via mobile and b) will edit the url of the group profile to something different than the group name?

**Comment by boonebgorges** [comment]
Thanks, @agmckinney. This seems like a fairly impactful problem, so I fixed it. On smaller screens, the URL fields now break into a second line. See screenshot.

![screenshot_2018-07-20_14-47-24](https://user-images.githubusercontent.com/246627/43008994-025d2150-8c2c-11e8-84c7-020e62e2c6cb.png)

**Comment by agmckinney** [comment]
Fixed! Thanks, Boone!
