### ISSUE TITLE
Calendar: Recurring events don't work

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#247]
When creating a new calendar event or editing a previously created calendar event you can set the event to be recurring successfully but it does not apply successfully to the calendar itself. See this event: http://openlabdev.commonsinabox.org/groups/mmobile-projectobil/events/recurring-event-2/
In edit mode it shows that the event is recurring: 
![screen shot 2018-07-20 at 12 02 55 pm](https://user-images.githubusercontent.com/11300891/43012727-e904efba-8c14-11e8-8488-592328f8c4c4.png)
However, in the calendar it does not show as recurring: http://openlabdev.commonsinabox.org/calendar/

**Comment by bree-z** [comment]
This doesn't appear to be an issue now. :)
