### ISSUE TITLE
Categories not showing up

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#248]
In both group creation (all groups) and when editing the settings for a group after creation, the ability to add/delete categories associated with the group is missing.

In the admin panel under - "Group Settings: Group Categories" there are two categories that are set to different group types: 
![screen shot 2018-07-22 at 2 34 04 pm](https://user-images.githubusercontent.com/11300891/43048846-58ac8c1c-8dbc-11e8-8082-80eb0ba56ca3.png)

However, these group types do not have the ability to add/delete these categories. 

You can successfully filter groups by category in the group type directories, but nothing shows up. One assumes this is because group categories are not assigned to any group because of this issue.

**Comment by boonebgorges** [comment]
It appears that the Category interface was missed during the rebuild of the group creation/edit processes #138 . I've just readded it. Please give a try by creating/editing some groups.

**Comment by agmckinney** [comment]
This is fixed. Thanks, Boone!
