### ISSUE TITLE
Create course form with " " in description field redirects to creat club form

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/openlab-theme#250]
This is a weird one. If I try to [create a course](http://openlabdev.commonsinabox.org/groups/create/step/group-details/?group_type=course&new=true) and fill out all required fields, but enter only one or more space(s) (" ") in the description field, clicking "create and continue" then takes me to [club creation](http://openlabdev.commonsinabox.org/groups/create/step/group-details/?group_type=club). I'm not sure how best to document this. Let me know what further details to provide. I've recreated several times on Android 7+/Chrome 67+ and MacOS 10.13.5/Chrome 67+ and MacOs 10.13.5/Firefox 59+.

![screenshot-openlabdev commonsinabox org-2018 07 23-15-21-22_space-desc](https://user-images.githubusercontent.com/3885628/43098127-25988b98-8e8c-11e8-8c0f-1f27e5e28be7.png)

![screenshot-openlabdev commonsinabox org-2018 07 23-15-21-56](https://user-images.githubusercontent.com/3885628/43098130-26c99fc0-8e8c-11e8-85e3-b3487871a9e7.png)

**Comment by boonebgorges** [comment]
The client-side validation in openlab-theme uses the `required` attribute, which can be fooled by whitespace. But BuddyPress is doing the server-side validation, and it uses `trim()` or something like that.

Ideally, we'd have smarter client-side validation, but this requires writing something custom, which is not possible at this point. As a simple workaround, I've added a clause that converts the description value into a non-breaking space character if it's found to be made up of whitespace only, which is enough to fool BuddyPress.
