### ISSUE TITLE
Group settings: Red background of success message "Group details were successfully updated."

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/openlab-theme#253]
It seems wrong to me that a message like  "Group details were successfully updated" appears on a red background. I expected green or some neutral color.

![screenshot-openlabdev commonsinabox org-2018 07 23-15-45-02](https://user-images.githubusercontent.com/3885628/43099224-7d432a58-8e8f-11e8-846f-e72639141853.png)

```html
<div id="message" class="bp-template-notice updated">

			<p>Group details were successfully updated.</p>

		</div>
```

**Comment by boonebgorges** [comment]
We changed success feedback notices to have the red background as part of #134. Errors have yellow. See especially https://www.dropbox.com/sh/3ok9zru1eos7mn1/AADWFiIdd_QqvJL0WKRmUky9a/AccessibleColorThemes?dl=0&preview=CBOXOL-colorschemeBluev2.png cc @jennaspevack

**Comment by moui72** [comment]
Got it. Sorry for my oversight.
