### ISSUE TITLE
My Courses and My Projects

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#255]
The display on these pages is truncated (My Clubs and the other "My" pages are fine). I am testing on Chrome Dev Tools emulating iPhone 6,7,8 plus.
![truncated](https://user-images.githubusercontent.com/8832300/43168189-5a4f0fe0-8f6a-11e8-8b64-1862c0ed75fc.png)

**Comment by boonebgorges** [comment]
I'm unable to reproduce this. The avatars on your screenshot don't match what I see when I set the Dev Tools to 6/7/8+. This leads me to believe that your browser hasn't properly refreshed the styles when switching between different emulation modes. While in this mode, try doing a hard browser refresh (Shift + Refresh). 

Some resizing also takes place via JavaScript on page load, so it could be that you resized your viewport after initially loading the page. On my computer, I'm seeing what you're seeing above, but only as a brief flash, until the document is loaded; at that point, the JS does the necessary resizing. Please look to see if there are any JS errors in your console.

**Comment by sreal19** [comment]
It is looks correct now when I retest. I will close this.

**Comment by sreal19** [comment]
I have during testing other functions encountered this truncation again (so far only on Courses and Projects), so it seems to be intermittent or context dependent. I am going to reopen. Please let me know info I can give you to help find this possible bug.

**Comment by boonebgorges** [comment]
Thanks @sreal19. Could you please have a look at my comment above? 

- hard refresh
- view any errors in JS console
