### ISSUE TITLE
Breadcrumb People Link "Page Not Found"

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#257]
The breadcrumb for the My clubs page has a link to Home and People. Clicking the People link generates a Page not found. Same results on the Mobile emulator and the desktop browser (Chrome on Mac).
![breadcrumbs](https://user-images.githubusercontent.com/8832300/43168612-ef8ebde8-8f6b-11e8-9530-795952772a7f.png)

**Comment by boonebgorges** [comment]
Good catch. This was a carryover bit of hardcoding from OpenLab. I've made the fix.

**Comment by sreal19** [comment]
Looks good now.
