### ISSUE TITLE
Mobile > Group directories: 'Back to top' link doesn't appear 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#259]
The 'Top' link that links back to the top of a directory page on mobile doesn't appear on CBOX-OL, compared with the OpenLab.  

### CBOX-OL

![img_7457](https://user-images.githubusercontent.com/7189824/43209799-34f34f00-9036-11e8-9cef-d53b53809f72.PNG)

### OpenLab

![groupdirectory_toplink](https://user-images.githubusercontent.com/7189824/43209706-fe1f8f20-9035-11e8-9617-4b0aeb0d39bc.png)

**Comment by boonebgorges** [comment]
This was never ported from the OpenLab and was not caught in earlier testing. It's been added and is ready to test.

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good. The only issue is that it's teal, rather than the theme accent color.

**Comment by boonebgorges** [comment]
@bree-z I don't recall having the color indicated in any style guide, so I'm going to close this ticket, but flag it so that @jennaspevack can reopen with suggestions if she'd like.

**Comment by jennaspevack** [comment]
Sorry. I probably forgot about that little arrow. To simplify, maybe we can just make it light gray across the color schemes?

background: rgba(209, 209, 209, .42)

**Comment by boonebgorges** [comment]
Works for me. I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks!
