### ISSUE TITLE
Account Creation: Able to register without filling in required fields

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#261]
I'm able to register successfully without entering the following required fields:

- Account Type
- Email Address

For all other required fields, validation works correctly.

**Comment by boonebgorges** [comment]
I cannot reproduce with 'Email Address'. Can you please give more detailed instructions on exactly what you're entering?

I've added client-side validation for Account Type.

**Comment by bree-z** [comment]
Thanks, Boone!  Validation is working for Account Type.  

And sorry, I just realized I should have specified which email address field I was referring to!  The validation for email address in the Account Details section is working as expected.  However, in the Public Profile Details section, the Email Address field is marked as required, but I'm able to register without entering anything in the field. 

When I double check in Network Admin > Users > Profile fields, if I'm looking at the correct thing, it looks like Contact Information > Email Address is required.  

Here's where I'm looking at Email Address in the Contact Information tab: http://openlabdev.commonsinabox.org/wp-admin/network/users.php?page=bp-profile-setup

<img width="1247" alt="screen shot 2018-08-01 at 5 30 04 pm" src="https://user-images.githubusercontent.com/7189824/43528063-c6e49a7a-95b0-11e8-9237-496451da0466.png">

When I click on Edit, I end up on this page: http://openlabdev.commonsinabox.org/wp-admin/network/users.php?page=bp-profile-setup&mode=edit_field&group_id=8&field_id=12

<img width="1263" alt="screen shot 2018-08-01 at 5 29 41 pm" src="https://user-images.githubusercontent.com/7189824/43528180-09802110-95b1-11e8-9215-f23f417a5800.png">

And some screenshots of my sign up test:

<img width="918" alt="screen shot 2018-08-01 at 5 01 56 pm" src="https://user-images.githubusercontent.com/7189824/43528374-7b6729cc-95b1-11e8-929b-a0c09f53d092.png">

<img width="934" alt="screen shot 2018-08-01 at 5 02 12 pm" src="https://user-images.githubusercontent.com/7189824/43528380-8044ffe6-95b1-11e8-9076-f65c571bbf3e.png">

**Comment by boonebgorges** [comment]
Thanks for the additional details. I've added some validation so that it should no longer be possible to continue without filling in fields marked 'required'.
