### ISSUE TITLE
Admin: Default settings for Student and Alumni

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#267]
According to the testing sheet, the default setting for students should be "May changed to type alumni" but this is not the default setting:
![screen shot 2018-07-27 at 12 41 37 pm](https://user-images.githubusercontent.com/11300891/43334221-cab3d87e-919a-11e8-8922-bef60638806b.png)

The same problem occurs for the default alumni setting which should be able to be changed to student by default
![screen shot 2018-07-27 at 12 44 59 pm](https://user-images.githubusercontent.com/11300891/43334250-e4a812f4-919a-11e8-94d7-d15da4036493.png)

**Comment by boonebgorges** [comment]
Thanks for the find. This was due to a typo in the original implementation.

To test on the production site would mean doing a full reset, which I don't want to do in the midst of other testing, so I'm going to mark this resolved.
