### ISSUE TITLE
Admin: Member type name changes don't reflect on front end

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#268]
Hopefully I'm not dense and this isn't related to #265 but when a member type name is changed it takes on the back end (here "students" changed to "kids" and "alumni" changed to "alumna")
![screen shot 2018-07-27 at 1 11 48 pm](https://user-images.githubusercontent.com/11300891/43336371-b30326ae-919e-11e8-932f-9db413d5cb9d.png)
But this change doesn't take on the front end in sign-up: 
![screen shot 2018-07-27 at 12 59 59 pm](https://user-images.githubusercontent.com/11300891/43336391-c3e045ce-919e-11e8-8dfc-389b6fff5402.png)
Or in the member directory:
![screen shot 2018-07-27 at 12 58 09 pm](https://user-images.githubusercontent.com/11300891/43336400-ce9d1e9c-919e-11e8-93ef-395780a4d4ab.png)
Or on a profile of the changed type:
![screen shot 2018-07-27 at 1 00 20 pm](https://user-images.githubusercontent.com/11300891/43336421-df0fe5a2-919e-11e8-92ae-6d2c72a3b961.png)

**Comment by boonebgorges** [comment]
Publicly-visible labels are handled by the Labels section on the admin. See the "Singular" label at the bottom of the screenshot.

![screenshot_2018-07-27_14-09-50](https://user-images.githubusercontent.com/246627/43341972-c26c64ea-91a6-11e8-90a4-c491e18d37ac.png)

The "Name" at the top affects only how the item is listed in the Dashboard. That is, it's an admin-facing label.
