### ISSUE TITLE
Admin: Members cannot change type even if allowed

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#269]
The admin can assign the different member types that another member type can change to manually: 
![screen shot 2018-07-27 at 1 51 21 pm](https://user-images.githubusercontent.com/11300891/43340295-db072992-91a9-11e8-8beb-27226e7bfec8.png)

But this doesn't take on the front end when a user (in this case a student) tries to change their member type (in this case to alumni). The additional member type doesn't show:
![screen shot 2018-07-27 at 1 52 58 pm](https://user-images.githubusercontent.com/11300891/43340329-f4ec076a-91a9-11e8-9e3c-784474f0f44c.png)

**Comment by boonebgorges** [comment]
This should now be fixed.

**Comment by boonebgorges** [comment]
(I ended up having to reset some settings in order to make this testable, so if you see any of your custom group/member types gone, that's why.)

**Comment by agmckinney** [comment]
I was mildly confused for a second! This is fixed tho! Thanks, Boone!
