### ISSUE TITLE
Admin: Changes to member type plurals don't take on front end

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#270]
Likely related to #268 

When the plural of a member type is change it takes on the backend:
![screen shot 2018-07-27 at 2 47 18 pm](https://user-images.githubusercontent.com/11300891/43340950-0a69b018-91ac-11e8-9225-5a7cd9cf3b60.png)
But does not take on the front end:
![screen shot 2018-07-27 at 2 47 43 pm](https://user-images.githubusercontent.com/11300891/43340957-12b065b4-91ac-11e8-8f49-865abcc74176.png)

**Comment by boonebgorges** [comment]
Yes, this is the same issue as #268.
