### ISSUE TITLE
Not able to update plugins on openlabdev.commonsinabox.org

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#275]
Sorry for the late ticket, but as I was trying to refresh my memory about plugin updates to make sure the documentation is correct, I tried updating Anthologize and bbPress forums and wasn't able to update either.  In both cases, I saw the message that the update process was starting, maintenance mode was being enabled, but, both updates failed, with a similar message:

An error occurred while updating Anthologize: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions. 

![anthologizeupdateerror](https://user-images.githubusercontent.com/7189824/47315278-25660b00-d612-11e8-9e9e-b63ba127fda1.png)

![bbpressupdateerror](https://user-images.githubusercontent.com/7189824/47315280-25660b00-d612-11e8-8f5b-c82921e5ce83.png)

cc @charliemedwards

**Comment by boonebgorges** [comment]
I've just made a config change that may fix this. Please have a test. If it doesn't work, let me know what you need confirmed and I'll do some manual confirmation, as it may prove difficult to debug and loosen the permission schema on this specific site in advance of the documentation deadline.

**Comment by bree-z** [comment]
Thanks Boone!  I was able to successfully update Anthologize.
