### ISSUE TITLE
Braille settings remain in Group Settings after Braille plugin is deactivated

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#276]
And another apology for another late ticket!

After deactivating the Braille plugin in CBOX OL Dashboard > Plugins, I noticed that Braille settings still appear in Group settings, where it looks like the plugin is still available to be activated.  See, for example: http://openlabdev.commonsinabox.org/groups/political-writing/admin/group-settings/ or http://openlabdev.commonsinabox.org/groups/test-course-12345/admin/group-settings/ 

It does seem that the plugin has been deactivated since the Braille toggle doesn't appear in discussion forums.  And I see a notice that the plugin needs to be activated on this site: 
http://openlabdev.commonsinabox.org/political-writings/wp-admin/plugins.php

cc: @charliemedwards 

![braillesettings](https://user-images.githubusercontent.com/7189824/47315742-6b6f9e80-d613-11e8-9acc-237bef2d3287.png)

![braillesitewarnings](https://user-images.githubusercontent.com/7189824/47315743-6c083500-d613-11e8-9dd3-e0f5e84d5ac5.png)

**Comment by boonebgorges** [comment]
There appear to be two separate issues here:

1. BP Braille appears on site dashboards, but should not. @r-a-y Does CBOX have the ability to hide certain plugins (like those that should be activated only on the main site, via the CBOX tools) from this list? Perhaps making them 'Network: true' is the best way? 

2. Turning off some parts of the Braille system (BP Braille + the main Braille plugin) doesn't properly turn off some parts of the front-end interface. @bree-z Can you please give more details here? When you say "After deactivating the Braille plugin in CBOX OL Dashboard > Plugins", exactly what do you mean? Do you mean turned off "Braille Support" at http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional ? I have a feeling there's some confusion here about network-activation of the Braille tools (which affect the main site) and Braille activation on subsites (which does not affect the main site).

**Comment by r-a-y** [comment]
The reason BP Braille is visible is because CBOX appears to be operating in Expert Mode (the `CBOX_OVERRIDE_PLUGINS` define is set to true) on the test site.

Once Expert Mode is turned off, site admins shouldn't see BP Braille in their plugins list.

Can you confirm, @boonebgorges?

**Comment by boonebgorges** [comment]
Aha! You were right, @r-a-y. I've disabled the setting and the problem in 1 appears to have gone away. Bree, please confirm.

**Comment by bree-z** [comment]
Thanks, Boone. 

Re 1. I don't see BP Braille listed in the plugins list.

Re 2. Yes, I turned off "Braille Support" at http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional ?

But, the front-end settings interface still appears on individual Group Home settings pages (e.g. http://openlabdev.commonsinabox.org/groups/political-writing/admin/group-settings/ ) .  

Separately, I still see the Braille plugin available on subsites.  

I thought that turning off "Braille Support" at http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional would (1) hide the front-end settings interface on individual Group Home settings pages and (2) the Braille plugin would no longer appear in the plugins list on individual subsites. 

But, I could also be wrong about either of those!  And apologies if I'm still not explaining this properly!

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the details, Bree.

> I thought that turning off "Braille Support" at http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional would (1) hide the front-end settings interface on individual Group Home settings pages and (2) the Braille plugin would no longer appear in the plugins list on individual subsites.

You're correct about #1, but it wasn't working properly in some cases. I've tightened the logic in 2702b76b1a6155c5cfff71c88e8dd579382eb258 and it should now be working.

You're incorrect about #2. Whether Braille appears on subsites is controlled by the "Member Site Plugins' panel.

**Comment by bree-z** [comment]
Thanks, Boone.  

1: I no longer see the Braille settings on the front-end, so this looks good, thanks!

2: The only place I see a Braille plugin is 'Braille Support' in the Community Features panel (http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional).  There's no Braille plugin listed in the Member Site Plugins panel (http://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=install-only), unless I'm looking in the wrong place.  I also don't see it listed in Network Admin > Plugins

![screen shot 2018-10-23 at 6 23 46 pm](https://user-images.githubusercontent.com/7189824/47394831-53bb1780-d6f2-11e8-814f-04745be5b71e.png)

One last thing is that now when I go to the plugins list on a subsite when logged in as a regular non-superadmin member (e.g. http://openlabdev.commonsinabox.org/writing-politics-sp2018-pol345/wp-admin/plugins.php logged in as testfaculty, the admin for that subsite), I see a message at the top that probably shouldn't be there:  

CBOX Network Plugins
You can manage your CBOX plugins here.

![screen shot 2018-10-23 at 6 37 40 pm](https://user-images.githubusercontent.com/7189824/47395058-228f1700-d6f3-11e8-9853-7e2855fdbb1a.png)

Thanks!

**Comment by boonebgorges** [comment]
Thanks, Bree. The issues you've referenced are not necessarily straightforward fixes, and likely cannot be addressed for the 1.1.0 release. I've opened tickets on the commons-in-a-box repo (linked above) to track them.

Since the primary issue here is resolved, I'm closing the ticket.

**Comment by bree-z** [comment]
Thanks Boone!
