### ISSUE TITLE
Styling missing for blog post pages

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/openlab-theme#285]
Reported here:
https://commonsinabox.org/groups/openlab-help-support/forum/topic/posts-title-and-body-not-rendering/

Blog post pages need to be styled similar to regular pages.  Also the comments markup either needs revising or just CSS additions.

**Comment by boonebgorges** [comment]
Thanks for noticing this, @r-a-y. It should be straightforward to ensure at least basic functionality for the next Commons In A Box release. I'm going to create a corresponding ticket there.
