### ISSUE TITLE
"Associated Site Details" issues

### ISSUE THREAD

**Issue by Mamaduka** [cuny-academic-commons/openlab-theme#293]
Hi @boonebgorges,

I found two issues when testing custom navigation menus (had to create a lot of groups 😃).

* An associated site HTML is escaped.
* When creating a new group "Set up a site?" site is hidden. I think this [condition](https://github.com/cuny-academic-commons/openlab-theme/blob/1.2.x/lib/group-funcs.php#L217) should be reversed.

**Screenshots**
<img width="843" alt="Screenshot-n71kj" src="https://user-images.githubusercontent.com/240569/87782513-b39d0e80-c843-11ea-9f02-422db991b917.png">
<img width="844" alt="Screenshot-7eick" src="https://user-images.githubusercontent.com/240569/87782517-b566d200-c843-11ea-94ee-76e03f928737.png">

**Comment by boonebgorges** [comment]
Whoops :-D Thanks for catching these.

For future reference, could you please open tickets only against the main commons-in-a-box repo? The issues here are for legacy use only.

**Comment by Mamaduka** [comment]
Sure thing.
