### ISSUE TITLE
Fatal error when viewing a discussion topic with no group type

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/openlab-theme#304]
Probably an edge case when I was testing from switching over from Classic to OpenLab, but when viewing a group topic and when there is no existing group type for the group, a fatal error will occur:

> PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_label() in \wp-content\openlab-theme\bbpress\content-single-topic.php:69

See:
https://github.com/cuny-academic-commons/openlab-theme/blob/47f8b1322372e1c92098bfb8d5923e1b3aaba0fe/bbpress/content-single-topic.php#L69

Not sure if we want to add some type of fallback if a group type does not exist.

**Comment by boonebgorges** [comment]
Yeah, it's an edge case, but one that I've tried to account for elsewhere. I'll push a fix.
