### ISSUE TITLE
"Terms of service" etc language on signup page

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#92]
The registration page, pulled from the OpenLab, has the language from the following screenshot:

![screenshot_2017-10-17_15-59-41](https://user-images.githubusercontent.com/246627/31675388-021d1cba-b354-11e7-8adf-dc0674dbfe33.png)

We can't be sure that sites will have a Terms of Service and Privacy Policy (though we can certainly encourage them to do so). What should we do about the text? Just remove it?

**Comment by bree-z** [comment]
Sorry to just be getting to this now! 

The functionality works well -- I can make changes to or eliminate the text.  The only issue is that there's no feedback that changes were saved, after clicking the save button.  The button is highlighted, but there's no page reload or change in the button appearance.  

![tos](https://user-images.githubusercontent.com/7189824/40076194-42fc95c4-584c-11e8-8ad4-c583e6981957.png)

**Comment by boonebgorges** [comment]
Thanks, @bree-z ! We don't really have much in the way of visual success/failure indications anywhere in the dashboard, and it's too late for design/implementaton of those sorts of things. So let's mark this one complete, and cover that issue separatel.
